# Generated by Django 3.1.14 on 2023-05-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_prn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectoffstudy',
            name='consent_model',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectoffstudy',
            name='consent_version',
        ),
        migrations.RemoveField(
            model_name='subjectoffstudy',
            name='consent_model',
        ),
        migrations.RemoveField(
            model_name='subjectoffstudy',
            name='consent_version',
        ),
        migrations.AddField(
            model_name='historicalsubjectoffstudy',
            name='action_identifier',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectoffstudy',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectoffstudy',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubjectoffstudy',
            name='tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subjectoffstudy',
            name='action_identifier',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='subjectoffstudy',
            name='parent_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subjectoffstudy',
            name='related_tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subjectoffstudy',
            name='tracking_identifier',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
